services:
  registry-admin:
    container_name: registry-admin
    image: ${IMAGE:-localhost/registry-admin:latest}
    restart: unless-stopped
    # command: sleep infinity
    environment:
      APP_UID: ${APP_UID:-1001}
      RA_DEBUG: ${RA_DEBUG:-false}
      RA_REGISTRY_HOSTNAME: ${RA_REGISTRY_HOSTNAME:-0.0.0.0}
      RA_REGISTRY_HOST: ${RA_REGISTRY_HOST}
      RA_REGISTRY_PORT: ${RA_REGISTRY_PORT}
      RA_AUTH_TOKEN_SECRET: ${RA_AUTH_TOKEN_SECRET}
      RA_STORE_DB_TYPE: ${RA_STORE_DB_TYPE:-embed}
      RA_STORE_ADMIN_PASSWORD: ${RA_STORE_ADMIN_PASSWORD}
      RA_STORE_EMBED_DB_PATH: ${RA_STORE_EMBED_DB_PATH:-/app/data/store.db}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    volumes:
      - registry-admin-data:/app/data
    networks:
      - distribution-network

volumes:
  registry-admin-data:
    name: registry-admin-data

networks:
  distribution-network:
    external: true