services:
  registry-admin:
    volumes:
      - step-ca-certs:/certs
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-80}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - step-ca-network

volumes:
  step-ca-certs:
    external: true

networks:
  step-ca-network:
    name: step-ca-network
    external: true