services:
  registry-admin:
    environment:
      STEP_CA_TRUST: ${STEP_CA_TRUST:-true}
      STEP_CA_TRUST_RESTART: ${STEP_CA_TRUST_RESTART:-true}
      REQUESTS_CA_BUNDLE: ${REQUESTS_CA_BUNDLE:-/etc/ssl/certs/ca-certificates.crt}
      SSL_CERT_FILE: ${SSL_CERT_FILE:-/etc/ssl/certs/ca-certificates.crt}
